#!/bin/sh

# Gives an external feedback to the user, to inform on the success or failure of the NuvlaBox installation
# $1 can be SUCCESS, ERROR or START, corresponding to the different phases and states of the NuvlaBox installation

state="${1}"

if [ "${state}" = "SUCCESS" ]
then
  echo heartbeat > /sys/class/leds/led0/trigger
  sleep 5
  echo mmc0 > /sys/class/leds/led0/trigger
fi


if [ "${state}" = "ERROR" ]
then
  echo timer > /sys/class/leds/led0/trigger
  sleep 5
  echo mmc0 > /sys/class/leds/led0/trigger
fi


if [ "${state}" = "START" ]
then
  echo default-on > /sys/class/leds/led0/trigger
  sleep 5
  echo mmc0 > /sys/class/leds/led0/trigger
fi